### ISSUE TITLE
MCQ - Difficulty label gradient

### ISSUE THREAD

**Issue by Pinguu** [LeCoinEnBande/OOnoz#100]
We need a gradient for display the difficulty of the MCQ (/OOnozAdministration/Questionnaires).

Column "Difficulté"  --> the label generated are _difficulty-LEVEL_ (replace LEVEL by [1,2,3,4 or 5])

[https://puu.sh/tonlB/55d48838d2.png](https://puu.sh/tonlB/55d48838d2.png)

**Comment by jecisc** [comment]
Done
