### ISSUE TITLE
We need a logo for the tab

### ISSUE THREAD

**Issue by jecisc** [LeCoinEnBande/OOnoz#15]
It could be cool to have a logo for the tab in the browser. When the logo will be add it can be set in the application inside the OORoot>>#updateRoot: method.

@JoeLaBidouille I think that this task suit you :)

**Comment by maximepiquet** [comment]
I'm on it

**Comment by jecisc** [comment]
You don't have to hurry since the kickoff is more urgent :)

**Comment by maximepiquet** [comment]
I't will be added soon, since I need an SVG.

**Comment by jecisc** [comment]
Need integration

**Comment by jecisc** [comment]
Finished on: dcadffd25a0e623e895e697734b7681dd9c8c168
