### ISSUE TITLE
Implements Marking Schemes

### ISSUE THREAD

**Issue by jecisc** [LeCoinEnBande/OOnoz#25]
- [x] Declare OOAbstractMarkingSchemeStrategyTest as abstract
- [x] Implements the model
- [x] Documentation
- [x] Use marking scheme in questions

**Comment by Pinguu** [comment]
TODO --> documentation ("de la vraie" _Cyril_)

**Comment by jecisc** [comment]
For now the questions does not have the marking scheme as composition. I will add tests to add this later.

**Comment by Pinguu** [comment]
Documentation added

**Comment by jecisc** [comment]
In https://github.com/LeCoinEnBande/OOnoz/pull/26
