### ISSUE TITLE
Maquette correction

### ISSUE THREAD

**Issue by jecisc** [LeCoinEnBande/OOnoz#30]
Listing:
- [x] Title without space break the table
- [x] Cross to close info
- [x] Alert

Creation/Edition
- [x] Buttons (Info, ...)
- [x] Delete buttons
- [x] Cancel buttons (style + layout)
- [x] Make it beautiful
- [x] **Make it fast**

**Comment by jecisc** [comment]
@maximepiquet I think this can be close with the last push?

**Comment by maximepiquet** [comment]
I think we can close that
