### ISSUE TITLE
Play: Maquette

### ISSUE THREAD

**Issue by jecisc** [LeCoinEnBande/OOnoz#41]

**Comment by jecisc** [comment]
@maximepiquet After first version we need at least to add:
- [ ] Price
- [x] Theme
- [x] Subtheme
- [ ] Order of questions
- [ ] Note (User notation of the mcq)
- [x] Reset button is type button instead of reset
- [x] No description for a question
- [x] Title of 35px is enough
- [x] Need a validation button
- [x] A description of the question kind should be added with emphasis
- [x] Need separators between questions
- [x] Radio buttons
- [x] Colors of correction
- [ ] Head of correction page

**Comment by jecisc** [comment]
@maximepiquet I added some things. You already know most of them but with that we will not lose it.

**Comment by maximepiquet** [comment]
Reset button can't be a reset button because it will reset all the answers, and not the selected one.

**Comment by jecisc** [comment]
:(

**Comment by maximepiquet** [comment]
Yeah, I know, I will add some JS for doing that :)

**Comment by jecisc** [comment]
No need of JS to reset I did it in Seaside
@maximepiquet I begun to update the missing things in the list

**Comment by maximepiquet** [comment]
I need to find some icons for the init page, because actually it's a lot of text, and I don't like it
