### ISSUE TITLE
Basic MCQ 

### ISSUE THREAD

**Issue by jecisc** [LeCoinEnBande/OOnoz#5]
Missing:
- [x] Title of MCQ

**Comment by jecisc** [comment]
First basic version in: https://github.com/LeCoinEnBande/OOnoz/pull/21

I will open new issues later when the teacher will answer our questions in order to finish the content of this feature.

**Comment by jecisc** [comment]
The model is almost complete on: https://github.com/LeCoinEnBande/OOnoz/pull/26

**Comment by jecisc** [comment]
Now I am waiting for @maximepiquet's sketch.

**Comment by maximepiquet** [comment]
Now, GFY

**Comment by jecisc** [comment]
Done with sprint 1.
